### PR TITLE
Add no-std compatibility

### LINKED ISSUE #25: Add no_std support
Thank you very much for this crate, it really simplifies the usage for decoding / encoding of Substrate types from metadata. We'd like to use scale-decode (and encode) for the [substrate-api-client](https://github.com/scs/substrate-api-client), but for this we need `no-std` support.

I'd happily provide the PR for this, but there are two caveats:
- `thiserror` is not no-std compatible. AFAIK, there's no simple workaround
- currently, `error_in_core` is a nightly feature only.

So I'm not sure how open you are to a PR in this regard. If you're still interested, I did some work in a fork:
- Decode: https://github.com/scs/scale-decode/pull/1
- Encode: https://github.com/scs/scale-encode/pull/1

Happy to share and adapt if you see a solution for the caveats above.

### PR DESCRIPTION
**Pull request by haerdib**
Add no-std feature gate:
- `no_std` is activated in case of deactivated `std` feature
- removes `thiserror` because it's not no-std compatible
- removes `full` feature from codec import (deprecated)

CI changes:
- Adds a `Check no_std build`
- Adds extra crate `testing/no_std` to ensure scale-encode-derive is no_std by CI

closes #25

### CODE REVIEW

**Comment by jsdw** [comment]
I'm out for a few days so apologies if I'm a bit slow to look at this; I'll try to find time soon though!

**Comment by haerdib** [comment]
There's no hurry from my side, so take your time 👍

**Review by altaua — APPROVED** [review]

**Review by jsdw — APPROVED** [review]
Sorry for the delay; it's been a busy last couple of weeks!

This looks amazing; great job!

**Review by tadeohepperle — APPROVED** [review]
Looks good!

**Review by lexnv — APPROVED** [review]

**Pull request merged**
